### PR TITLE
r23 SDK and NotificationCompat

### PR DESCRIPTION
**Pull request by vitalyster**
Deprecated Notification APIs was removed from SDK 23, using support-v4 library now

### CODE REVIEW

**Comment by Flowdalic** [comment]
See also #46 and #47

**Comment by Flowdalic** [comment]
And for the record, this is basically the same as https://github.com/redsolution/MemorizingTrustManager/commit/144bd3d06e99f2e618054abe70228c74f95e1fac minus the `compileOptions` setting to 1.7.

**Comment by vitalyster** [comment]
And ant support missing there :)

**Comment by ge0rg** [comment]
I have merged #46 now, which performs the same change but in a backwards-compatible way.

**Pull request closed without merging**
