### PR TITLE
Do not ignore expired exception

### PR DESCRIPTION
**Pull request by mimi89999**
Tested on LineageOS 17.1 (Android 10).

### CODE REVIEW

**Comment by ge0rg** [comment]
Thanks for the submission. Did you check if the removal of that special case will properly fall-back to the `isCertKnown()` branch and accept the expired-but-known certs?

**Comment by mimi89999** [comment]
I tested with https://expired.badssl.com/. Should I perform additional testing?

**Comment by ge0rg** [comment]
That domain is the right one, the question would be: does it warn you on first access, does it auto-accept the cert if you pressed "always" before.

**Comment by mimi89999** [comment]
> That domain is the right one, the question would be: does it warn you on first access, does it auto-accept the cert if you pressed "always" before.

Yes, yes.

**Pull request closed without merging**
